### ISSUE TITLE
Rightclick uninstall not available from Cinnamenu (Grid)

### ISSUE THREAD

**Issue by AlanSmythe** [fredcw/Cinnamenu.json#1]
Hello,
I am pleased to see Cinnamenu added back to Linux Mint. When I saw, I switched as soon as I noticed. 

I noticed however, that when I right click, I there is no option to uninstall software. Is it possible to add uninstall software from right click in Cinnamenu?

(Note: This is when in grid style, it appears to be there in list style.)

**Comment by fredcw** [comment]
I can't reproduce this bug. When "uninstall" appears in list view, it also appears in grid view for me. Are you using Linux Mint?

**Comment by fredcw** [comment]
@AlanSmythe I can't reproduce this bug. When "uninstall" appears in list view, it also appears in grid view for me. Are you using Linux Mint?

**Comment by AlanSmythe** [comment]
> @AlanSmythe I can't reproduce this bug. When "uninstall" appears in list view, it also appears in grid view for me. Are you using Linux Mint?

I guess I should have said I was using a theme. I realize when using the stock Cinnamon theme, it then shows up. But when using the Windows 10 theme that is in the Mint theme store, it then reproduces the issue.

So the issue was my theme, the Windows 10 theme that is in the Mint theme downloads.

**Comment by fredcw** [comment]
@AlanSmythe That is indeed a strange bug. The option appears and then disappears within a second. I may look into this at some point but atm, I'm not sure if the fault lies with the applet, cinnamon or the theme. I'm busy rn but I'll look into if I have time. Thanks for reporting.
